name: alrayada
description: An ecommerce application developed by Fresh Platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Packages
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  path: ^1.8.3
  # dio_cache_interceptor: ^3.4.2
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1

  flutter_platform_widgets: ^6.0.2
  cupertino_stepper: ^0.2.1

  web_socket_channel: ^2.4.0
  flutter_svg: ^2.0.9

  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  linkify_plus: ^6.0.0

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  shared_alrayada:
    path: ./shared
  
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.3

#  settings_ui: ^2.0.2
#  auto_size_text_plus: ^3.0.1
#  zaincash: ^0.0.5
# adaptive_navigation: ^0.0.9

  # Plugins
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  # firebase_core: ^2.24.2
  # firebase_crashlytics: ^3.4.8
  # firebase_analytics: ^10.7.4
  # firebase_messaging: ^14.6.1
  onesignal_flutter: ^5.0.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/payment_methods/
    - assets/images/
    - assets/images/payment_methods/
    - assets/lottie/
    - assets/lottie/no_internet/
    - assets/lottie/page_not_found/

flutter_gen:

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

