name: alrayada_admin
description: A admin appliaction for alrayada created by Fresh Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  # pretty_dio_logger: ^1.3.1
  # shared_preferences: ^2.1.1
  # flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # fluent_ui: ^4.6.2
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.1
  file_picker: ^6.1.1
  printing: ^5.11.1
  desktop_drop: ^0.4.4
  web_socket_channel: ^2.4.0
  flutter_riverpod: ^2.4.9

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  shared_alrayada:
    path: ../shared

  # window_manager: ^0.3.0

  # window_size:
  #   git:
  #     url: https://github.com/google/flutter-desktop-embedding
  #     path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true