name: alrayada_admin
description: A admin appliaction for alrayada created by Ahmed Hnewa
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2
  # pretty_dio_logger: ^1.3.1
  # shared_preferences: ^2.1.1
  # flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  # fluent_ui: ^4.6.2
  url_launcher: ^6.1.14
  cached_network_image: ^3.2.3
  file_picker: ^5.5.0
  printing: ^5.11.0
  desktop_drop: ^0.4.3
  web_socket_channel: ^2.4.0
  flutter_riverpod: ^2.4.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  shared_alrayada:
    path: ../shared_alrayada

  # window_manager: ^0.3.0

  # window_size:
  #   git:
  #     url: https://github.com/google/flutter-desktop-embedding
  #     path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  flutter_gen_runner: ^5.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true